# Copyright © 2017–2019 University of Malta

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.

before_script:
  - getconf LONG_BIT
  - rustup --version
  - rustup install beta-$TARGET 1.37.0-$TARGET
  - rustup component add --toolchain beta-$TARGET rustfmt clippy
  - if [ -d cargo/registry/cache ]; then rm -rf $CARGO_HOME/registry/cache; mkdir -p $CARGO_HOME/registry; cp -R cargo/registry/cache $CARGO_HOME/registry/; echo Copied registry/cache; fi
  - if [ -d $CARGO_HOME/registry/cache ]; then (cd $CARGO_HOME/registry; find cache -name \*.crate) fi

after_script:
  - if [ -d $CARGO_HOME/registry/cache ]; then (cd $CARGO_HOME/registry; find cache -name \*.crate) fi
  - rm -rf cargo
  - mkdir -p cargo/registry
  - if [ -d $CARGO_HOME/registry/cache ]; then cp -R $CARGO_HOME/registry/cache cargo/registry/; echo Updated registry/cache; fi

x86_64-gnulinux:
  image: amd64/rust:1
  variables:
    TARGET: x86_64
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
  script:
  - cargo +beta-$TARGET test --features fail-on-warnings
  - cargo +beta-$TARGET test --release --features fail-on-warnings
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --all-targets --features fail-on-warnings
  - cargo +1.37.0-$TARGET test --features fail-on-warnings
  - cargo +1.37.0-$TARGET test --release --features fail-on-warnings
  except:
  - www

i686-gnulinux:
  image: i386/rust:1
  variables:
    TARGET: i686
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
  script:
  - cargo +beta-$TARGET test --features fail-on-warnings
  - cargo +beta-$TARGET test --release --features fail-on-warnings
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --all-targets --features fail-on-warnings
  - cargo +1.37.0-$TARGET test --features fail-on-warnings
  - cargo +1.37.0-$TARGET test --release --features fail-on-warnings
  except:
  - www

x86_64-gnulinux-sys-libs:
  image: amd64/rust:1
  variables:
    TARGET: x86_64
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
  script:
  - apt-get -y update
  - apt-get -y install libgmp-dev libmpfr-dev libmpc-dev
  - cargo +beta-$TARGET test --features "fail-on-warnings use-system-libs"
  - cargo +beta-$TARGET test --release --features "fail-on-warnings use-system-libs"
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --all-targets --features "fail-on-warnings use-system-libs"
  - cargo +1.37.0-$TARGET test --features "fail-on-warnings use-system-libs"
  - cargo +1.37.0-$TARGET test --release --features "fail-on-warnings use-system-libs"
  except:
  - www

i686-gnulinux-sys-libs:
  image: i386/rust:1
  variables:
    TARGET: i686
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
  script:
  - apt-get -y update
  - apt-get -y install libgmp-dev libmpfr-dev libmpc-dev
  - cargo +beta-$TARGET test --features "fail-on-warnings use-system-libs"
  - cargo +beta-$TARGET test --release --features "fail-on-warnings use-system-libs"
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --all-targets --features "fail-on-warnings use-system-libs"
  - cargo +1.37.0-$TARGET test --features "fail-on-warnings use-system-libs"
  - cargo +1.37.0-$TARGET test --release --features "fail-on-warnings use-system-libs"
  except:
  - www

pages:
  image: alpine:latest
  before_script:
  - "true"
  script:
  - "true"
  after_script:
  - "true"
  artifacts:
    paths:
    - public
  only:
  - www
