x86_64-gnulinux:
  image: amd64/rust:1
  variables:
    TARGET: x86_64
  script:
  - rustup --version
  - rustup install beta-$TARGET 1.13.0-$TARGET
  - rustup component add --toolchain beta-$TARGET rustfmt clippy
  - export GMP_MPFR_SYS_CACHE=$PWD/gmp-mpfr-sys-cache
  - cargo +beta-$TARGET test --features "fail-on-warnings ctest"
  - cargo +beta-$TARGET test --release --features fail-on-warnings
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --release --all-targets --features fail-on-warnings
  - cargo +1.13.0-$TARGET test --features fail-on-warnings
  - cargo +1.13.0-$TARGET test --release --features fail-on-warnings
  except:
  - www

i686-gnulinux:
  image: i386/rust:1
  variables:
    TARGET: i686
  script:
  - rustup --version
  - rustup install beta-$TARGET 1.13.0-$TARGET
  - rustup component add --toolchain beta-$TARGET rustfmt clippy
  - export GMP_MPFR_SYS_CACHE=$PWD/gmp-mpfr-sys-cache
  - cargo +beta-$TARGET test --features "fail-on-warnings ctest"
  - cargo +beta-$TARGET test --release --features fail-on-warnings
  - cargo +beta-$TARGET fmt -- --check
  - cargo +beta-$TARGET clippy --release --all-targets --features fail-on-warnings
  - cargo +1.13.0-$TARGET test --features fail-on-warnings
  - cargo +1.13.0-$TARGET test --release --features fail-on-warnings
  except:
  - www

pages:
  script:
  - "true"
  artifacts:
    paths:
    - public
  only:
  - www
