gnulinux-beta:
  image: rust:1
  before_script:
  - rustup install beta
  - cargo +beta --version
  - rustc +beta --version
  - mkdir cache
  - export GMP_MPFR_SYS_CACHE=cache
  script:
  - cargo +beta test --release
  - cargo +beta test
  except:
  - www

gnulinux-1.13.0:
  image: rust:1
  before_script:
  - rustup install 1.13.0
  - cargo +1.13.0 --version
  - rustc +1.13.0 --version
  - mkdir cache
  - export GMP_MPFR_SYS_CACHE=cache
  script:
  - cargo +1.13.0 test --release
  - cargo +1.13.0 test
  except:
  - www

pages:
  script:
  - "true"
  artifacts:
    paths:
    - public
  only:
  - www
